name: test

on:
  push:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install --frozen-lockfile
      - run: yarn test
